packages:
  - src/dashboard-ui

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - lmdb
  - msgpackr-extract
  - protobufjs
  - sharp

onlyBuiltDependencies:
  - esbuild
  - onnxruntime-node
  - tree-sitter-go
  - tree-sitter-javascript
  - tree-sitter-rust
  - tree-sitter-typescript
